version: "1.0"

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "tienda"
      MYSQL_USER: "dani"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
