@API=http://localhost:8080

### Index
GET {{API}}

### Get all users
GET {{API}}/api/users

### Get a user
GET {{API}}/api/users/1

### Create a user
POST {{API}}/api/users
Content-Type: application/json

{
  "name": "angela",
  "email": "angelnaa@mail.com",
  "password": "123456",
  "role": "user",
  "address": "le park",
  "phone": 2222222
}

### Update a user
PUT {{API}}/api/users/2
Content-Type: application/json

{
  "name": "Steven Manani",
  "email": "humber@mail.com",
  "password": "11231236",
  "role": "moderator",
  "address": "viva la Gloria",
  "phone": 23232323
}

### Delete a user
DELETE {{API}}/api/users/2

#_______AUTH__________

### login
POST {{API}}/api/auth/login/signin
Content-Type: application/json

{
  "email": "Jack@mail.com",
  "password": "123456"
}

### route auth
GET {{API}}/api/productos
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6IkphY2tAbWFpbC5jb20iLCJpYXQiOjE2NTM3ODI3MTYsImV4cCI6MTY1NDM4NzUxNn0.un3LKKOd3IADYxqzHFByrRiyRCsr-ituv133WoObpv0

