@API=http://localhost:8080

### Index
GET {{API}}

### Get all users
GET {{API}}/api/users

### Get a user
GET {{API}}/api/users/2

### Create a user
POST {{API}}/api/users
Content-Type: application/json

{
  "name": "Markitos",
  "email": "Mark@mail.com",
  "password": "123456",
  "role": "moderator",
  "address": "avenida siempre viva",
  "phone": 111111111
}

### Update a user
PUT {{API}}/api/users/2
Content-Type: application/json

{
  "name": "Humberti Gonzales",
  "email": "humber@mail.com",
  "password": "11231236",
  "role": "moderator",
  "address": "viva la Gloria",
  "phone": 23232323
}

### Delete a user
DELETE {{API}}/api/users/1